name: CI
on:
  push:
    branches: [master]
  pull_request:
jobs:
  ci:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-ci.yml@0c6624ebbfd7e7f93a448163c241111768d86541 # v1.0.5
    with:
      node-versions: '[20, 22, 24]'
      has-build: false
