name: CI
on:
  push:
    branches: [master]
  pull_request:
jobs:
  ci:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-ci.yml@0a154f2464d678b83874a47b5abe3c33fa29fb83 # main
    with:
      node-versions: '[20, 22, 24]'
      has-build: false
