name: commitlint
on:
  pull_request:
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@5389d699374234e7a2c9f5ca6101c6e53168c796 # v1.0.4
