name: commitlint
on:
  pull_request:
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@8209b3759f567166a64a0e5e3a26652b154ed360 # v1.0.2
