name: commitlint
on:
  pull_request:
jobs:
  commitlint:
    permissions:
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-commitlint.yml@d493a18373453d0e55c5e9952d472f59763f3da2 # v1.0.0
