name: publish
on:
  release:
    types: [published]
permissions:
  contents: read
  id-token: write   # required for OIDC on the calling job
jobs:
  publish:
    permissions:
      contents: read
      id-token: write
    uses: unabandoned/.github/.github/workflows/reusable-publish.yml@4c62f69814fcf517f1c9baa02f4105fce18e6c7f # v1.0.1
    with:
      install-for-publish: false
    secrets: inherit
