name: release-please
on:
  push:
    branches: [master]
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@8209b3759f567166a64a0e5e3a26652b154ed360 # v1.0.2
    secrets: inherit
