name: release-security
on:
  pull_request:
    types: [closed]
jobs:
  security-release:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-security.yml@3259184528f6d99057e8f6e204790cf04b5efc2f # v1.2.1
    secrets: inherit
