name: release-please
on:
  push:
    branches: [master]
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@6be3bc531cad43d59a76021ac2fd338892b3a1fe # main
    secrets: inherit
