name: release-please
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-please.yml@bd9eb6bfc5a567b272e0c6f05703a726a2655531 # v1.1.0
    secrets: inherit
