name: release-security
on:
  pull_request:
    types: [closed]
jobs:
  security-release:
    permissions:
      contents: write
      pull-requests: write
    uses: unabandoned/.github/.github/workflows/reusable-release-security.yml@0a154f2464d678b83874a47b5abe3c33fa29fb83 # main
    secrets: inherit
