name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [master]
jobs:
  scorecard:
    permissions:
      security-events: write
      id-token: write
      contents: read
    uses: unabandoned/.github/.github/workflows/reusable-scorecard.yml@3259184528f6d99057e8f6e204790cf04b5efc2f # v1.2.1
