name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 6 * * 1'
  push:
    branches: [master]
jobs:
  scorecard:
    uses: unabandoned/.github/.github/workflows/reusable-scorecard.yml@ab6594761eb1a6aee92bbb84c1ea333c02346e3a # main
